[default]
    IS_PRODUCTION = false
    URL_ROOT_PATH = '/'  # Переопределяется при использовании reverse-proxy
    METRICS_ENABLED = true

    LOGGER_CONFIG = "configs/log_cfg.yaml"
    ENCODING = "utf-8"

    PATH_TO_MODELS = 'artifacts/models'
    CLASSIFIER_ONNX_MODEL = 'ru-bert.onnx'
    THRESHOLD = 0.5

    RUN_SERVER_COMMAND = "main:app_factory"
    RUN_SERVER_HOST = "0.0.0.0"
    RUN_SERVER_PORT = 10052
    RUN_SERVER_ACCESS_LOG = true
    RUN_SERVER_LOG_LEVEL = "info"
    RUN_SERVER_FACTORY = true
    RUN_SERVER_DEBUG_RELOAD = true

    SERVICE_TITLE = "rag-service"
    SERVICE_DESCRIPTION = ""
    SERVICE_VERSION = "0.1.0"

    PATH_TO_INDEX = "artifacts/dictionaries/gu_faqs.pqt"

    CACHE_HOST_REDIS = "localhost"
    CACHE_PORT_REDIS = 6379

    SIZE_CHARS = 128
    REDIS_HASHER = "hashlib_sha512"

[K8S_DEV]

[K8S_DEV01]

[K8S_DEV02]

[K8S_UAT]
